# MurderAddon 配置文件
# Configuration file for MurderAddon

# 语言设置 / Language Settings
language: "zh_CN"  # 支持: zh_CN, en_US

# 尸体设置 / Corpse Settings
corpse:
  # 尸体存在时间（秒）/ Corpse duration in seconds
  # 设置为 -1 表示尸体在游戏结束前一直存在 / Set to -1 to keep corpses until game ends
  duration: -1
  
  # 是否显示尸体名称 / Show corpse name
  show-name: true
  
  # 尸体名称格式 / Corpse name format
  # 占位符: {player} - 死亡玩家名称
  name-format: "&7{player} 的尸体"
  
  # 是否隐藏在玩家列表中 / Hide from tab list
  hide-from-tab-list: true
  
  # 尸体生成位置偏移 / Corpse spawn position offset
  position-offset:
    # X轴偏移 / X-axis offset
    x: 0.5
    # Y轴偏移（高度） / Y-axis offset (height)
    y: 0.0
    # Z轴偏移 / Z-axis offset
    z: 0.0

  # 尸体朝向设置 / Corpse rotation settings
  rotation:
    # 朝向模式 / Rotation mode
    # 可选值 / Available options:
    # - KEEP_DEATH: 保持死亡时的朝向 / Keep death rotation
    # - FIXED: 固定朝向 / Fixed rotation
    # - RANDOM: 随机朝向 / Random rotation
    mode: "KEEP_DEATH"

    # 固定朝向设置（仅在mode为FIXED时生效）/ Fixed rotation settings (only effective when mode is FIXED)
    fixed:
      # 水平朝向（0-360度）/ Horizontal rotation (0-360 degrees)
      yaw: 0.0
      # 垂直朝向（-90到90度）/ Vertical rotation (-90 to 90 degrees)
      pitch: 0.0

# 亡语设置 / Death message settings
death-message:
  # 是否启用自定义亡语浮空字时间 / Enable custom death message floating text duration
  enabled: false

  # 亡语浮空字显示时间（秒）/ Death message floating text duration in seconds
  # 设置为 -1 使用 MurderMystery 默认时间 / Set to -1 to use MurderMystery default duration
  duration: 5

  # 亡语浮空字高度偏移 / Death message floating text height offset
  height-offset: 1.0

# 调试设置 / Debug Settings
debug:
  # 是否启用调试模式 / Enable debug mode
  # 建议在遇到问题时启用，可以帮助诊断问题 / Recommended to enable when troubleshooting
  enabled: false

  # 调试消息前缀 / Debug message prefix
  prefix: "&8[&6MurderAddon-Debug&8]&7 "

# 高级设置 / Advanced Settings
advanced:
  # 尸体创建延迟（tick）/ Corpse creation delay in ticks
  # 增加此值可能有助于解决尸体创建失败的问题 / Increasing this may help with corpse creation failures
  corpse-creation-delay: 10

  # 游戏状态检查延迟（tick）/ Game state check delay in ticks
  game-state-check-delay: 40
